# Generated by Django 3.2.10 on 2022-03-10 01:00

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(help_text='작성자 입력', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', markdownx.models.MarkdownxField(help_text='제목 입력')),
                ('body', markdownx.models.MarkdownxField(help_text='검색할 내용 입력')),
            ],
        ),
    ]
