# Generated by Django 3.2.10 on 2022-05-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposeidon_app', '0002_rename_body_userdata_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
